### ISSUE TITLE
QR scanner error

### ISSUE THREAD

**Issue by btclinux** [airgap-it/airgap-vault#148]
Android 8 EMUI. When tap on Scanner button

other 1656505706694

Error:
Uncaught (in promise): TypeError: Cannot read property 'ɵmod' of undefined
TypeError: Cannot read property 'ɵmod' of undefined
    at getNgModuleDef (http://localhost/main.412b00552a6a9cf20ea6.js:1:7120050)
    at new NgModuleFactory$1 (http://localhost/main.412b00552a6a9cf20ea6.js:1:7247551)
    at Compiler_compileModuleSync__POST_R3__ (http://localhost/main.412b00552a6a9cf20ea6.js:1:7262715)
    at Compiler_compileModuleAsync__POST_R3__ [as compileModuleAsync] (http://localhost/main.412b00552a6a9cf20ea6.js:1:7262811)
    at MergeMapSubscriber.project (http://localhost/main.412b00552a6a9cf20ea6.js:1:8461540)
    at MergeMapSubscriber._tryNext (http://localhost/main.412b00552a6a9cf20ea6.js:1:3139193)
    at MergeMapSubscriber._next (http://localhost/main.412b00552a6a9cf20ea6.js:1:3139078)
    at MergeMapSubscriber.next (http://localhost/main.412b00552a6a9cf20ea6.js:1:3304301)
    at http://localhost/main.412b00552a6a9cf20ea6.js:1:6057639
    at ZoneDelegate.invoke (http://localhost/polyfills.806eec13c09d8ffd7baa.js:1:7609)
Error: Uncaught (in promise): TypeError: Cannot read property 'ɵmod' of undefined
TypeError: Cannot read property 'ɵmod' of undefined
    at getNgModuleDef (http://localhost/main.412b00552a6a9cf20ea6.js:1:7120050)
    at new NgModuleFactory$1 (http://localhost/main.412b00552a6a9cf20ea6.js:1:7247551)
    at Compiler_compileModuleSync__POST_R3__ (http://localhost/main.412b00552a6a9cf20ea6.js:1:7262715)
    at Compiler_compileModuleAsync__POST_R3__ [as compileModuleAsync] (http://localhost/main.412b00552a6a9cf20ea6.js:1:7262811)
    at MergeMapSubscriber.project (http://localhost/main.412b00552a6a9cf20ea6.js:1:8461540)
    at MergeMapSubscriber._tryNext (http://localhost/main.412b00552a6a9cf20ea6.js:1:3139193)
    at MergeMapSubscriber._next (http://localhost/main.412b00552a6a9cf20ea6.js:1:3139078)
    at MergeMapSubscriber.next (http://localhost/main.412b00552a6a9cf20ea6.js:1:3304301)
    at http://localhost/main.412b00552a6a9cf20ea6.js:1:6057639
    at ZoneDelegate.invoke (http://localhost/polyfills.806eec13c09d8ffd7baa.js:1:7609)
    at resolvePromise (http://localhost/polyfills.806eec13c09d8ffd7baa.js:1:18884)
    at resolvePromise (http://localhost/polyfills.806eec13c09d8ffd7baa.js:1:18349)
    at http://localhost/polyfills.806eec13c09d8ffd7baa.js:1:19868
    at ZoneDelegate.invokeTask (http://localhost/polyfills.806eec13c09d8ffd7baa.js:1:8342)
    at Object.onInvokeTask (http://localhost/main.412b00552a6a9cf20ea6.js:1:7265912)
    at ZoneDelegate.invokeTask (http://localhost/polyfills.806eec13c09d8ffd7baa.js:1:8263)
    at Zone.runTask (http://localhost/polyfills.806eec13c09d8ffd7baa.js:1:3243)
    at drainMicroTaskQueue (http://localhost/polyfills.806eec13c09d8ffd7baa.js:1:10926)
    at ZoneTask.invokeTask [as invoke] (http://localhost/polyfills.806eec13c09d8ffd7baa.js:1:9599)
    at invokeTask (http://localhost/polyfills.806eec13c09d8ffd7baa.js:1:24255)

**Comment by AndreasGassmann** [comment]
Hi, thanks for your report.

Does the camera work when you generate a new secret? This would help us narrow down if it's a general camera issue, or if it's related to the QR scanner specifically.

**Comment by OneAndNobody** [comment]
Hi, I'm experiencing the same issue on an HTC One S running LineageOS 14.1 (Android 7.1.2) with up-to-date System Webview. The camera works when generating a secret.

**Comment by dim0xff** [comment]
Looks like #79 (problem with zxing/ngx-scanner scanner)
