### ISSUE TITLE
Bug in Metamask with QR

### ISSUE THREAD

**Issue by Ufymau** [airgap-it/airgap-vault#183]
After adding the address by QR code from the phone, after a while the metamask closed with this error.
MetaMask [10.24.2]
AirGap Vault [v3.20.0]

Сообщение: Cannot read properties of undefined (reading 'balance')

Код: TypeError

Стек:
TypeError: Cannot read properties of undefined (reading 'balance')
  at n.isBalanceCached (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-7.js:1:134123)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:200583
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:201080
  at R (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-5.js:1:408886)
  at ha (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:59903)
  at Cu (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:104661)
  at El (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:90577)
  at bl (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:90502)
  at fl (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:87850)
  at al (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:84618)
  at Yl (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:112222)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:113421
  at dl (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:88198)
  at es (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:113406)
  at render (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:115323)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-7.js:1:29975

**Comment by Ufymau** [comment]
After some time in error, MM started up. But this happens every time after adding a QR wallet.
Also, my QR code does not confirm my transactions, it says that QR was not found, although the same QR connects my addresses perfectly. I also tried to use QR from a specific address, it does not work either.

**Comment by Ufymau** [comment]
Repeated the error after the restoration of the work.
When adding, it works fine, after closing / opening the MM an error appears. Time didn't help
this time, how the omission of the error occurs is not clear.

**Comment by AndreasGassmann** [comment]
Is the address in MetaMask the same as you have in AirGap Vault? Because if the account/address is displayed correctly in MetaMask, then I don't think this is related to AirGap Vault.
